apiVersion: v2
name: resource-action
description: Helm chart for creating generic ResourceAction resources
type: application
version: 0.3.2
appVersion: "0.3.2"
keywords:
  - kubernetes
  - resourceaction
  - http
  - jobs
  - automation
home: https://github.com/zdmr-space/Resource-Action-Operator
sources:
  - https://github.com/zdmr-space/Resource-Action-Operator
maintainers:
  - name: Resource Action Operator Maintainers
