apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger-nginx-a
  namespace: ra-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger-nginx-a
  template:
    metadata:
      labels:
        app: trigger-nginx-a
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
