version: 0.2.0-rc4
name: resource-action-operator
displayName: Resource Action Operator
description: |
  Kubernetes operator to execute HTTP and Job actions on resource lifecycle events.
type: operator
license: Apache-2.0
homeURL: https://github.com/zdmr-space/Resource-Action-Operator
keywords:
  - operator
  - kubernetes
  - automation
  - webhook
maintainers:
  - name: Yusa Ozdemir
    email: mail@yusaozdemir.de
