apiVersion: ops.yusaozdemir.de/v1alpha1
kind: ResourceAction
metadata:
  name: namespace-create-cron
spec:
  selector:
    group: ""
    version: v1
    kind: Namespace
  events:
    - Create
  actions:
    - type: http
      mode: cron
      schedule: "*/2 * * * *"
      method: POST
      url: https://httpbin.org/post
---
apiVersion: ops.yusaozdemir.de/v1alpha1
kind: ResourceAction
metadata:
  name: namespace-delete-once
spec:
  selector:
    group: ""
    version: v1
    kind: Namespace
  events:
    - Delete
  actions:
    - type: http
      mode: once
      method: POST
      url: https://httpbin.org/post

