apiVersion: ops.yusaozdemir.de/v1alpha1
kind: ResourceAction
metadata:
  name: deployment-tls-hook
  namespace: ra-demo
spec:
  selector:
    group: apps
    version: v1
    kind: Deployment
  events:
    - Create
    - Delete
  filters:
    namespaceRegex: "^ra-demo$"
    nameRegex: "^trigger-nginx-.*$"
  actions:
    - type: http
      mode: once
      method: POST
      url: https://ra-nginx-tls.ra-demo.svc.cluster.local:8443/hook
      expectedStatus: "^2..$"
      timeout: 10s
      tls:
        serverName: ra-nginx-tls.ra-demo.svc.cluster.local
        caSecretRef:
          name: ra-nginx-ca
          key: ca.crt
      body:
        template: |
          {
            "channel": "tls",
            "event": "{{ .metadata.name }}",
            "resource": {
              "name": "{{ .metadata.name }}",
              "namespace": "{{ .metadata.namespace }}",
              "uid": "{{ .metadata.uid }}"
            }
          }
