apiVersion: v2
name: resource-action-operator
description: Kubernetes operator for event-driven HTTP and Job actions on Kubernetes resources
type: application
version: 0.2.0-rc8
appVersion: "0.2.0-rc8"
keywords:
  - kubernetes
  - operator
  - webhook
  - automation
home: https://github.com/zdmr-space/Resource-Action-Operator
sources:
  - https://github.com/zdmr-space/Resource-Action-Operator
maintainers:
  - name: Resource Action Operator Maintainers
