apiVersion: ops.yusaozdemir.de/v1alpha1
kind: ResourceAction
metadata:
  name: node-label-http-hook
  namespace: default
spec:
  selector:
    group: ""
    version: v1
    kind: Node
  events:
    - Update
  filters:
    labels:
      demo.resource-action-operator/enabled: "true"
  actions:
    - type: http
      mode: once
      method: POST
      url: http://ra-http-sink.demo-http-sink.svc.cluster.local/hook
      expectedStatus: "^2..$"
      timeout: 10s
      body:
        template: |
          {
            "channel": "node-http",
            "node": "{{ .metadata.name }}",
            "labels": {{ .metadata.labels | toJson }}
          }
