---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-action-operator-job-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-action-operator-job-runner
subjects:
  - kind: ServiceAccount
    name: resource-action-operator-controller-manager
    namespace: resource-action-operator-system
---
apiVersion: ops.yusaozdemir.de/v1alpha1
kind: ResourceAction
metadata:
  name: namespace-job-bash
  namespace: default
spec:
  selector:
    group: ""
    version: v1
    kind: Namespace
  events:
    - Create
  filters:
    nameRegex: "^demo-job-trigger-.*$"
  actions:
    - type: job
      mode: once
      job:
        allowRunAsRoot: true
        image: ubuntu
        interpreterCommand:
          - /bin/bash
          - -c
        script: |
          echo "namespace trigger matched"
          date
          sleep 1m
        timeout: 30s
        ttlSecondsAfterFinished: 300
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-action-operator-job-runner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
